//保存商品信息 
// export const GET_CURRENT_GOODS_REQUEST = 'GET_CURRENT_GOODS_REQUEST';
// export const GET_CURRENT_GOODS_SUCCESS = 'GET_CURRENT_GOODS_SUCCESS';
// export const GET_CURRENT_GOODS_FAILURE = 'GET_CURRENT_GOODS_FAILURE';

//currentid
export const CURRENT_GOODS_ID = 'CURRENT_GOODS_ID';

//cookie
export const RECEIVE_COOKIE = 'RECEIVE_COOKIE';

//plan

// export const AVAILABLE_PLANS_REQUEST = 'AVAILABLE_PLANS_REQUEST';
// export const AVAILABLE_PLANS_SUCCESS = 'AVAILABLE_PLANS_SUCCESS';
// export const AVAILABLE_PLANS_FAILURE = 'AVAILABLE_PLANS_FAILURE';